## Python Numpy

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.
Besides its obvious scientific uses, Numpy can also be used as an efficient multi-dimensional container of generic data.

### Arrays in numpy

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.

### Creating a numpy array

Arrays in Numpy can be created by multiple ways, with various number of Ranks, defining the size of the Array. Arrays can also be created with the use of various data types such as lists, tuples, etc. The type of the resultant array is deduced from the type of the elements in the sequences.

### Numpy Arrays from Python List/Tuple Object

In [1]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list) #vector 1-d
print("Array with Rank 1: \n",arr)

Array with Rank 1: 
 [1 2 3]


In [2]:
arr.shape

(3,)

In [3]:
type(arr)

numpy.ndarray

In [0]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
arr = np.array(my_mat) #matrix 2-d
print("Array with Rank 2: \n",arr)

Array with Rank 2: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [0]:
# Creating an array from tuple
arr = np.array((1, 3, 2))
print("\nArray created using passed tuple:\n", arr)


Array created using passed tuple:
 [1 3 2]


## Numpy Methods

### arange() method returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)

#### Parameters:
start : [optional] start of interval range. By default start = 0

stop  : end of interval range

step  : [optional] step size of interval. By default step size = 1,  

dtype : type of output array

In [0]:
np.arange(0,10) #start,stop,step

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

### zeros() method returns a new array of given shape and type, with zeros.

#### Parameters :

shape : integer or sequence of integers

order  : C_contiguous or F_contiguous
         C-contiguous order in memory
         C order means that operating row-rise on the array 
         FORTRAN-contiguous order in memory
         F order means that column-wise operations 
         
dtype : [optional, float(byDeafult)] Data type of returned array.

In [0]:
np.zeros(3)

array([0., 0., 0.])

In [0]:
np.zeros(3, dtype=int)

array([0, 0, 0])

In [0]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [0]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### ones() method returns a new array of given shape and type, with ones.

#### Parameters :

shape : integer or sequence of integers

order  : C_contiguous or F_contiguous
         C-contiguous order in memory
         C order means that operating row-rise 
         FORTRAN-contiguous order in memory 
         F order means that column-wise operations
         
dtype : [optional, float(byDeafult)] Data type of returned array.

In [0]:
np.ones(4)

array([1., 1., 1., 1.])

In [0]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [0]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### linspace() method returns evenly spaced numbers over the specified intervals

In [0]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [0]:
np.linspace(0, 5, num=10, endpoint=False)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [0]:
np.linspace(0, 5, num=10, endpoint=True, retstep=True)

(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]),
 0.5555555555555556)

In [0]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

### Identity Matrix 
### eye() method returns a matrix having 1’s on the diagonal and 0’s elsewhere

In [0]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [0]:
np.eye(4,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]])

### identity() method returns an identity matrix i.e. a square matrix with ones on the main diagnol.

In [0]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Random samples from the uniform distribution from 0 to 1
### randon.rand() method creates an array of specified shape and fills it with random values.

In [0]:
np.random.rand(5)

array([0.42556786, 0.48489994, 0.96056159, 0.77572179, 0.84507598])

In [0]:
np.random.rand(5,5)

array([[0.94207279, 0.37418209, 0.01528245, 0.81873062, 0.38697866],
       [0.97635761, 0.58052821, 0.44959919, 0.51776398, 0.74435295],
       [0.03979843, 0.09004562, 0.24905119, 0.20430293, 0.60204201],
       [0.74423021, 0.57950025, 0.27734298, 0.8221512 , 0.13460256],
       [0.48297441, 0.26393384, 0.3076806 , 0.720991  , 0.85835148]])

### Random sample from the Standard Normal Distribution or Gaussian Distribution (Standard Normal Distribution centred around 0)
### random.randn(d0, d1, …, dn) : creates an array of specified shape and fills it with random values as per standard normal distribution
### If positive arguments are provided, randn generates an array of shape (d0, d1, …, dn), filled with random floats sampled from a univariate “normal” (Gaussian) distribution of mean 0 and variance 1

In [0]:
np.random.randn(2)

array([-0.14882295,  1.42642565])

In [0]:
np.random.randn(4,4)

array([[ 1.34007387, -0.63033348,  0.73752668,  1.23332482],
       [-1.01859952, -0.0412877 , -1.28754157, -2.7160341 ],
       [-0.87658254,  1.24531429,  0.21412328, -0.87348341],
       [ 1.18536461, -0.15243963,  1.065411  , -0.34492578]])

### Random Integers from lower to Higher Number

In [0]:
np.random.randint(1,100) #Lower inclusive, Higher Exclusive

79

In [0]:
np.random.randint(1,100,10)

array([59, 52,  4, 79, 39, 34, 53, 33, 70, 91])

### reshape() Method shapes an array without changing data of array.

In [0]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [0]:
arr.reshape(5,10)

ValueError: cannot reshape array of size 25 into shape (5,10)

### max() and min() methods

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.max()

24

In [0]:
arr.min()

0

### Location of max and min values using argmax() and argmin() Methods
#### argmax() method returns indices of the max element of the array in a particular axis.
#### argmin() method returns indices of the min element of the array in a particular axis.

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.argmax()

24

In [0]:
arr.argmin()

0

### Shape Attribute

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.shape

(25,)

In [0]:
randarr = np.random.randint(0,50,10).reshape(2,5)

In [0]:
randarr.shape

(2, 5)

### dtype attribute (datatype)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [0]:
arr.dtype

dtype('int32')

In [0]:
np.zeros(4).dtype

dtype('float64')

In [0]:
np.ones(3).dtype

dtype('float64')

### Numpy Indexing and Selection

In [0]:
arr = np.arange(11)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Numpy Indexing on Vectors

In [0]:
arr[8]

8

### Numpy Slicing on Vectors

In [0]:
arr[1:5] # start:stop #Bounded Slicing

array([1, 2, 3, 4])

In [4]:
arr

array([1, 2, 3])

In [5]:
arr[::-1]

array([3, 2, 1])

In [0]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [0]:
arr[:5] #Unbounded Slicing

array([0, 1, 2, 3, 4])

In [0]:
arr[5:] #Unbounded Slicing

array([ 5,  6,  7,  8,  9, 10])

In [0]:
slice_of_arr = arr[0:6] # It's just a reference, it won't create new object in the memory

In [0]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [0]:
slice_of_arr[:] = 99

In [0]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [0]:
arr #It has made the changes in the original array as well

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy = arr.copy() #It will create new object in the memory

In [0]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [0]:
arr_copy[:] = 100

In [0]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [0]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Numpy Indexing on 2-d array

In [0]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [0]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [0]:
arr_2d[0][0] #0-row, 0-column

5

In [0]:
arr_2d[0] #0-row

array([ 5, 10, 15])

In [0]:
arr_2d[1][1] #1-row, 1-column

25

In [0]:
arr_2d[1,2] #More Preferrable approach, 1-row and 2-column

30

### Numpy Slicing on 2-d array 

In [0]:
arr_2d[:2,1:] #Unbounded slicing

array([[10, 15],
       [25, 30]])

In [0]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [0]:
arr_2d = np.arange(50).reshape(5,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [0]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

## Conditional Selection

In [0]:
arr = np.arange(1,11)

In [0]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
bool_arr = arr > 5

In [0]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [0]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [0]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [0]:
arr[arr<3]

array([1, 2])

### Numpy Operations
#### 1. Array with Array
#### 2. Array with Scalars
#### 3. Universal Array Functions

In [0]:
arr = np.arange(11)

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Array with Array

In [0]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [0]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [0]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Array with scalars

In [0]:
arr + 100 #broadcast that scalar to each element in the array

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [0]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [0]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [0]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

### Numpy Array special datatype

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
arr/arr # nan --> null object 0/0

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [0]:
1/arr # inf object 1/0

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

### Universal Array Functions

In [0]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [0]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [0]:
np.max(arr)

10

In [0]:
arr.max()

10

In [0]:
np.min(arr)

0

In [0]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [0]:
np.log(arr) # log(0)=-inf

F:\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#### Reference Doc - https://docs.scipy.org/doc/numpy/reference/ufuncs.html

## Assignment
### 1. Numpy Excercise
### 2. Numpy problems from Hackerrank